// <auto-generated />
using System;
using Kuziemski_Zalewski_LAB08_09PZ_BK;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuziemski_Zalewski_LAB08_09PZ_BK.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230523163201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Kuziemski_Zalewski_LAB08_09PZ_BK.Wydarzenie", b =>
                {
                    b.Property<int>("WydarzenieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Koniec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Poczatek")
                        .HasColumnType("TEXT");

                    b.HasKey("WydarzenieId");

                    b.ToTable("Wydarzenia");
                });
#pragma warning restore 612, 618
        }
    }
}
